Update Fourbytes and Asset urls to be env variables
wmitsuda/otterscan pull request #17
Opened 2021-07-06 16:41 UTC by androolloyd

Update the fourbytes and asset endpoints to accept a ENV variable.

2021-07-06 16:41 UTC, androolloyd commented
if these get merged i can stop using my forked repo in the otterscan + erigon package.

2021-07-07 01:26 UTC, wmitsuda requested changes
I liked your idea, but can you pls make some changes? Also, please don't remove the package-lock.json, it is meant to be versioned, can you restore it in the PR (github doesn't let me comment on deletions).

2021-07-07 01:26 UTC, wmitsuda commented on src/components/MethodName.tsx
> +    const fourBytesURL = process.env.FOUR_BYTES_URL ? process.env.FOUR_BYTES_URL : "http://localhost:3001"
I think it is better to extract this constant and export it in params.ts. Also in Typescript, you can use the ?? operator, e.g., process.env.FOUR_BYTES_URL ?? "http://localhost:3001". See: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing

Lastly, I think this won't in a production build, React requires env variables to be prefix with REACT_APP, as explained here: https://create-react-app.dev/docs/adding-custom-environment-variables/

Could you make those changes, pls?

2021-07-07 01:26 UTC, wmitsuda commented on src/components/TokenLogo.tsx
> +  const assetsURL = process.env.ASSETS_URL ? process.env.ASSETS_URL : "http://localhost:3002";
Could make the same changes as above?

2021-07-07 01:47 UTC, wmitsuda commented
Also, feel free to contribute with your experience here: https://github.com/wmitsuda/otterscan/discussions/20

I'd like to make the user experience less painful for people who just want to run it.

2021-07-10 00:15 UTC, wmitsuda commented
I'll close this PR, since now all assets are distributed under 1 unique docker image.

Thanks for the effort anyway, feel free to open another issue if you want to suggest more improvements.

2021-07-10 00:15 UTC, closed without merging